# Tool settings
export OLLAMA_CODE_MAX_CONCURRENCY="5"
export OLLAMA_CODE_TOOL_TIMEOUT="60000"
export OLLAMA_CODE_APPROVAL_REQUIRED="true"

# Cache settings
export OLLAMA_CODE_CACHE_ENABLED="true"
export OLLAMA_CODE_CACHE_TTL="300000"
export OLLAMA_CODE_CACHE_MAX_SIZE="1000"